server:
  port: 80

spring:
  main:
    web-application-type: reactive
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes[0]:
        id: user-service
        uri: lb://user-service
        predicates[0]: Path=/user-service/**
        filters: StripPrefix=1
      routes[1]:
        id: party-service
        uri: lb://party-service
        predicates[0]: Path=/party-service/**
        filters: StripPrefix=1
      routes[2]:
        id: member-service
        uri: lb://member-service
        predicates[0]: Path=/member-service/**
        filters: StripPrefix=1
      routes[3]:
        id: bill-service
        uri: lb://bill-service
        predicates[0]: Path=/bill-service/**
        filters: StripPrefix=1
      routes[4]:
        id: notification-service
        uri: lb://notification-service
        predicates[0]: Path=/notification-service/**
        filters: StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# Actuator Prometheus Endpoint
management:
  endpoints:
    web:
      exposure:
        include: prometheus

jwt:
  variables:
    jwtSecret: 6MensTalk1Andy2Simon3Roy4Po5Jimmy6BuddySideProject0SplittingBill0
    jwtExpirationMs: 10800000