server:
  port: 80

spring:
  main:
    web-application-type: reactive
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      routes[0]:
        id: user-service
        uri: lb://user-service
        predicates[0]: Path=/api/user/**
        predicates[1]: Path=/api/auth/**
        filters[0]: WebFluxSecurityConfig
      routes[1]:
        id: party-service
        uri: lb://party-service
        predicates[0]: Path=/api/party/**
        filters[0]: SecurityWebFilterChain
      routes[2]:
        id: member-service
        uri: lb://member-service
        predicates[0]: Path=/api/member/**
        filters[0]: SecurityWebFilterChain
      routes[3]:
        id: bill-service
        uri: lb://bill-service
        predicates[0]: Path=/api/bill/**
        filters[0]: SecurityWebFilterChain
      routes[4]:
        id: notification-service
        uri: lb://notification-service
        predicates[0]: Path=/api/notification/**
        filters[0]: SecurityWebFilterChain

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# Actuator Prometheus Endpoint
management:
  endpoints:
    web:
      exposure:
        include: prometheus

jwt:
  variables:
    jwtSecret: menstalk
    jwtExpirationMs: 1800000