server:
  port: 8400

spring:
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1.0
  datasource: # DataSource
    url: jdbc:mysql://localhost:3306/notification_service?serverTimezone=Asia/Taipei
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: # SessionFactory
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.menstalk.notificationservice.domain.Notification

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

# Actuator Prometheus Endpoint
management:
  endpoints:
    web:
      exposure:
        include: prometheus